name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@2.1.0
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@1.4.1
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: gumlet
        ASSETS_DIR: wordpress-plugin-assets
